// Copyright (c) Christopher D. Dickson <cdd@matoya.group>
//
// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT License was not distributed with this file,
// You can obtain one at https://spdx.org/licenses/MIT.html.

#pragma once

static const VkFormat FMT_PLANES[MTY_COLOR_FORMAT_MAX][3] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = {VK_FORMAT_UNDEFINED,                VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_BGRA]       = {VK_FORMAT_B8G8R8A8_UNORM,           VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_RGBA]       = {VK_FORMAT_R8G8B8A8_UNORM,           VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_BGR565]     = {VK_FORMAT_R5G6B5_UNORM_PACK16,      VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_BGRA5551]   = {VK_FORMAT_A1R5G5B5_UNORM_PACK16,    VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_AYUV]       = {VK_FORMAT_B8G8R8A8_UNORM,           VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_Y410]       = {VK_FORMAT_A2R10G10B10_UNORM_PACK32, VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_Y416]       = {VK_FORMAT_R16G16B16A16_UNORM,       VK_FORMAT_UNDEFINED,    VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_2PLANES]    = {VK_FORMAT_R8_UNORM,                 VK_FORMAT_R8G8_UNORM,   VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_3PLANES]    = {VK_FORMAT_R8_UNORM,                 VK_FORMAT_R8_UNORM,     VK_FORMAT_R8_UNORM},
	[MTY_COLOR_FORMAT_2PLANES_16] = {VK_FORMAT_R16_UNORM,                VK_FORMAT_R16G16_UNORM, VK_FORMAT_UNDEFINED},
	[MTY_COLOR_FORMAT_3PLANES_16] = {VK_FORMAT_R16_UNORM,                VK_FORMAT_R16_UNORM,    VK_FORMAT_R16_UNORM},
};
