// Copyright (c) Christopher D. Dickson <cdd@matoya.group>
//
// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT License was not distributed with this file,
// You can obtain one at https://spdx.org/licenses/MIT.html.

#pragma once

static const GLenum FMT_PLANE0[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_RGBA,
	[MTY_COLOR_FORMAT_BGRA]       = GL_RGBA,
	[MTY_COLOR_FORMAT_NV12]       = GL_R8,
	[MTY_COLOR_FORMAT_I420]       = GL_R8,
	[MTY_COLOR_FORMAT_I444]       = GL_R8,
	[MTY_COLOR_FORMAT_NV16]       = GL_R8,
	[MTY_COLOR_FORMAT_BGR565]     = GL_RGB,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_RGBA,
	[MTY_COLOR_FORMAT_AYUV]       = GL_RGBA,
	[MTY_COLOR_FORMAT_Y410]       = GL_RGB10_A2,
	[MTY_COLOR_FORMAT_Y416]       = GL_RGBA16,
	[MTY_COLOR_FORMAT_P010]       = GL_R16,
	[MTY_COLOR_FORMAT_P016]       = GL_R16,
	[MTY_COLOR_FORMAT_I444_10]    = GL_R16,
	[MTY_COLOR_FORMAT_I444_16]    = GL_R16,
};

static const GLenum FMT_PLANE0_EXT[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_BGRA,
	[MTY_COLOR_FORMAT_BGRA]       = GL_BGRA,
	[MTY_COLOR_FORMAT_NV12]       = GL_RED,
	[MTY_COLOR_FORMAT_I420]       = GL_RED,
	[MTY_COLOR_FORMAT_I444]       = GL_RED,
	[MTY_COLOR_FORMAT_NV16]       = GL_RED,
	[MTY_COLOR_FORMAT_BGR565]     = GL_RGB,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_BGRA,
	[MTY_COLOR_FORMAT_AYUV]       = GL_BGRA,
	[MTY_COLOR_FORMAT_Y410]       = GL_BGRA,
	[MTY_COLOR_FORMAT_Y416]       = GL_BGRA,
	[MTY_COLOR_FORMAT_P010]       = GL_RED,
	[MTY_COLOR_FORMAT_P016]       = GL_RED,
	[MTY_COLOR_FORMAT_I444_10]    = GL_RED,
	[MTY_COLOR_FORMAT_I444_16]    = GL_RED,
};

static const GLenum FMT_PLANE0_TYPE[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_BGRA]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_NV12]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_I420]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_I444]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_NV16]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_BGR565]     = GL_UNSIGNED_SHORT_5_6_5,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_UNSIGNED_SHORT_1_5_5_5_REV,
	[MTY_COLOR_FORMAT_AYUV]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_Y410]       = GL_UNSIGNED_INT_2_10_10_10_REV,
	[MTY_COLOR_FORMAT_Y416]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_P010]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_P016]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_I444_10]    = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_I444_16]    = GL_UNSIGNED_SHORT,
};

static const GLenum FMT_PLANE1[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_RGBA,
	[MTY_COLOR_FORMAT_BGRA]       = GL_RGBA,
	[MTY_COLOR_FORMAT_NV12]       = GL_RG8,
	[MTY_COLOR_FORMAT_I420]       = GL_R8,
	[MTY_COLOR_FORMAT_I444]       = GL_R8,
	[MTY_COLOR_FORMAT_NV16]       = GL_RG8,
	[MTY_COLOR_FORMAT_BGR565]     = GL_RGB,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_RGBA,
	[MTY_COLOR_FORMAT_AYUV]       = GL_RGBA,
	[MTY_COLOR_FORMAT_Y410]       = GL_RGB10_A2,
	[MTY_COLOR_FORMAT_Y416]       = GL_RGBA16,
	[MTY_COLOR_FORMAT_P010]       = GL_RG16,
	[MTY_COLOR_FORMAT_P016]       = GL_RG16,
	[MTY_COLOR_FORMAT_I444_10]    = GL_R16,
	[MTY_COLOR_FORMAT_I444_16]    = GL_R16,
};

static const GLenum FMT_PLANE1_EXT[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_BGRA,
	[MTY_COLOR_FORMAT_BGRA]       = GL_BGRA,
	[MTY_COLOR_FORMAT_NV12]       = GL_RG,
	[MTY_COLOR_FORMAT_I420]       = GL_RED,
	[MTY_COLOR_FORMAT_I444]       = GL_RED,
	[MTY_COLOR_FORMAT_NV16]       = GL_RG,
	[MTY_COLOR_FORMAT_BGR565]     = GL_RGB,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_BGRA,
	[MTY_COLOR_FORMAT_AYUV]       = GL_BGRA,
	[MTY_COLOR_FORMAT_Y410]       = GL_BGRA,
	[MTY_COLOR_FORMAT_Y416]       = GL_BGRA,
	[MTY_COLOR_FORMAT_P010]       = GL_RG,
	[MTY_COLOR_FORMAT_P016]       = GL_RG,
	[MTY_COLOR_FORMAT_I444_10]    = GL_RED,
	[MTY_COLOR_FORMAT_I444_16]    = GL_RED,
};

static const GLenum FMT_PLANE1_TYPE[MTY_COLOR_FORMAT_MAX] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_BGRA]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_NV12]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_I420]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_I444]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_NV16]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_BGR565]     = GL_UNSIGNED_SHORT_5_6_5,
	[MTY_COLOR_FORMAT_BGRA5551]   = GL_UNSIGNED_SHORT_1_5_5_5_REV,
	[MTY_COLOR_FORMAT_AYUV]       = GL_UNSIGNED_BYTE,
	[MTY_COLOR_FORMAT_Y410]       = GL_UNSIGNED_INT_2_10_10_10_REV,
	[MTY_COLOR_FORMAT_Y416]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_P010]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_P016]       = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_I444_10]    = GL_UNSIGNED_SHORT,
	[MTY_COLOR_FORMAT_I444_16]    = GL_UNSIGNED_SHORT,
};
