// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT License was not distributed with this file,
// You can obtain one at https://spdx.org/licenses/MIT.html.

#pragma once

static const D3DFORMAT FMT_PLANES[MTY_COLOR_FORMAT_MAX][3] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = {D3DFMT_UNKNOWN,      D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGRA]       = {D3DFMT_A8R8G8B8,     D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_RGBA]       = {D3DFMT_A8B8G8R8,     D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGR565]     = {D3DFMT_R5G6B5,       D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGRA5551]   = {D3DFMT_X1R5G5B5,     D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_AYUV]       = {D3DFMT_A8R8G8B8,     D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_Y410]       = {D3DFMT_A2R10G10B10,  D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_Y416]       = {D3DFMT_A16B16G16R16, D3DFMT_UNKNOWN, D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_2PLANES]    = {D3DFMT_L8,           D3DFMT_A8L8,    D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_3PLANES]    = {D3DFMT_L8,           D3DFMT_L8,      D3DFMT_L8},
	[MTY_COLOR_FORMAT_2PLANES_16] = {D3DFMT_L16,          D3DFMT_G16R16,  D3DFMT_UNKNOWN},
	[MTY_COLOR_FORMAT_3PLANES_16] = {D3DFMT_L16,          D3DFMT_L16,     D3DFMT_L16},
};
