// Copyright (c) Christopher D. Dickson <cdd@matoya.group>
//
// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT License was not distributed with this file,
// You can obtain one at https://spdx.org/licenses/MIT.html.

#pragma once

static const DXGI_FORMAT FMT_PLANES[MTY_COLOR_FORMAT_MAX][3] = {
	[MTY_COLOR_FORMAT_UNKNOWN]    = {DXGI_FORMAT_UNKNOWN,            DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGRA]       = {DXGI_FORMAT_B8G8R8A8_UNORM,     DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_RGBA]       = {DXGI_FORMAT_R8G8B8A8_UNORM,     DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGR565]     = {DXGI_FORMAT_B5G6R5_UNORM,       DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_BGRA5551]   = {DXGI_FORMAT_B5G5R5A1_UNORM,     DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_AYUV]       = {DXGI_FORMAT_B8G8R8A8_UNORM,     DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_Y410]       = {DXGI_FORMAT_R10G10B10A2_UNORM,  DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_Y416]       = {DXGI_FORMAT_R16G16B16A16_UNORM, DXGI_FORMAT_UNKNOWN,      DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_2PLANES]    = {DXGI_FORMAT_R8_UNORM,           DXGI_FORMAT_R8G8_UNORM,   DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_3PLANES]    = {DXGI_FORMAT_R8_UNORM,           DXGI_FORMAT_R8_UNORM,     DXGI_FORMAT_R8_UNORM},
	[MTY_COLOR_FORMAT_2PLANES_16] = {DXGI_FORMAT_R16_UNORM,          DXGI_FORMAT_R16G16_UNORM, DXGI_FORMAT_UNKNOWN},
	[MTY_COLOR_FORMAT_3PLANES_16] = {DXGI_FORMAT_R16_UNORM,          DXGI_FORMAT_R16_UNORM,    DXGI_FORMAT_R16_UNORM},
};
